# This is a config for E2B sandbox template.
# You can use template ID (i9823ompf6ijuulbj0jm) or template name (line-nextjs-production) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("line-nextjs-production") # Sync sandbox
# sandbox = await AsyncSandbox.create("line-nextjs-production") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('line-nextjs-production')

team_id = "3c1640dc-38b1-4dba-8260-72a0a08aada6"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "line-nextjs-production"
template_id = "i9823ompf6ijuulbj0jm"
